---
AWSTemplateFormatVersion: 2010-09-09
Description: Creates a S3 bucket
Parameters:
  BucketName:
    Description: A bucket name
    Type: String
    AllowedPattern: "(?!^(d{1,3}.){3}d{1,3}$)(^[a-z0-9]([a-z0-9-]*(.[a-z0-9])?)*$)"
  BucketEncryptionType:
    Description: A bucket encryption type.
    Type: String
    AllowedValues:
      - SSE-S3
      - SSE-KMS
    Default: SSE-S3
  BucketEncryptionKey:
    Description: A bucket encryption key ARN.
    Type: String
    AllowedPattern: "^$|arn:(aws[a-zA-Z-]*)?:kms:[a-z]{2}((-gov)|(-iso(b?)))?-[a-z]+-d{1}:d{12}:key:.*"
    Default: ""
  Versioning:
    Description: Bucket versioning support.
    Type: String
    AllowedValues:
      - Enabled
      - Suspended
    Default: Suspended
  ObjectLockEnabled:
    Description: Object lock settings.
    Type: String
    AllowedValues:
      - true
      - false
    Default: false
  AccessControl:
    Description: Access control settings.
    Type: String
    AllowedValues:
      - Private
      - PublicRead
      - PublicReadWrite
      - AuthenticatedRead
      - LogDeliveryWrite
      - BucketOwnerRead
      - BucketOwnerFullControl
      - AwsExecRead
    Default: Private
  WebsiteEnabled:
    Description: A static website settings.
    Type: String
    AllowedValues:
      - true
      - false
    Default: false
  WebsiteIndexDocument:
    Description: A default website index document.
    Type: String
    Default: index.html
  WebsiteErrorDocument:
    Description: A default website error document.
    Type: String
    Default: error.html
Outputs:
  BucketName:
    Description: The bucket name
    Value: !Ref BucketName
    Export:
      Name: !Sub "${AWS::StackName}-BucketName"
  BucketARN:
    Description: A bucket resource name (ARN)
    Value: !If
      - WebsiteEnabled
      - !GetAtt
        - S3BucketWebsite
        - Arn
      - !GetAtt
        - S3Bucket
        - Arn
    Export:
      Name: !Sub "${AWS::StackName}-BucketARN"
Conditions:
  WebsiteEnabled: !Equals
    - !Ref WebsiteEnabled
    - true
  WebsiteDisabled: !Equals
    - !Ref WebsiteEnabled
    - false
  UseKMS: !Equals
    - !Ref BucketEncryptionType
    - SSE-KMS
Resources:
  S3Bucket:
    Type: "AWS::S3::Bucket"
    DeletionPolicy: Delete
    Condition: WebsiteDisabled
    Properties:
      BucketName: !Ref BucketName
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: !If [UseKMS, "aws:kms", "AES256"]
              KMSMasterKeyID: !If [UseKMS, !Ref BucketEncryptionKey, !Ref "AWS::NoValue"]
      VersioningConfiguration:
        Status: !Ref Versioning
      ObjectLockEnabled: !Ref ObjectLockEnabled
      AccessControl: !Ref AccessControl
      Tags:
        - Key: "Name"
          Value: !Ref BucketName

  S3BucketWebsite:
    Type: "AWS::S3::Bucket"
    DeletionPolicy: Delete
    Condition: WebsiteEnabled
    Properties:
      BucketName: !Ref BucketName
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: !If [UseKMS, "aws:kms", "AES256"]
              KMSMasterKeyID: !If [UseKMS, !Ref BucketEncryptionKey, !Ref "AWS::NoValue"]
      VersioningConfiguration:
        Status: !Ref Versioning
      ObjectLockEnabled: !Ref ObjectLockEnabled
      AccessControl: !Ref AccessControl
      WebsiteConfiguration:
        IndexDocument: !Ref WebsiteIndexDocument
        ErrorDocument: !Ref WebsiteErrorDocument
      Tags:
        - Key: "Name"
          Value: !Ref BucketName
...
